behaviors:
  Hider:
    trainer_type: poca
    hyperparameters:
      batch_size: 16000
      buffer_size: 160000
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512          
      num_layers: 3              
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 2500000
    max_steps: 30000000
    time_horizon: 500
    summary_freq: 100000
    threaded: false
    self_play:
      save_steps: 1000000
      team_change: 2000000
      swap_steps: 500000
      window: 50
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
  Seeker:
    trainer_type: poca
    hyperparameters:
      batch_size: 16000
      buffer_size: 160000
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512          
      num_layers: 3              
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 2500000
    max_steps: 30000000
    time_horizon: 500
    summary_freq: 100000
    threaded: false
    self_play:
      save_steps: 1000000
      team_change: 2000000
      swap_steps: 500000
      window: 50
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0