behaviors:
  HideAndSeek:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0002
      beta: 0.001
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 6                # Mehr Epochen für langfristiges Lernen
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024          # Höhere Kapazität für komplexe strategische Berechnungen
      num_layers: 3               # Weitere Layers für dynamischere Modelle
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 500
    summary_freq: 5000
    self_play:
      save_steps: 100000
      team_change: 100000         # Wechsel der Teams alle 100.000 Schritte
      swap_steps: 1000
      window: 5
      play_against_latest_model_ratio: 0.75 # Höheres Verhältnis zum aktuellen Modell
      initial_elo: 1200.0
